theme: onedark
# theme: catppuccin-mocha

apps:
  - aerospace
  - atuin
  - bat
  - fish
  - ghostty
  - git
  # - hyper
  - starship
  # - vscode # Only cspell user dictionary
  # - wezterm
  - yazi
  - zellij
  - worktrunk
  - nvim
  - karabiner
  - os/mac
  # - zsh
