"$schema" = 'https://starship.rs/config-schema.json'

format = """
$directory\
$git_branch\
$git_state\
$git_status\
$git_metrics\
$cmd_duration\
$jobs\
$status\
$python\
$fill\
$username\
$hostname\
$time\
$line_break\
$sudo\
$character"""

[fill]
symbol = " "

[directory]
truncation_length = 10
style = "blue bold"
fish_style_pwd_dir_length = 0
truncate_to_repo = false
home_symbol = "~"

[character]
success_symbol = "[❯](green)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

[git_branch]
format = "[$branch]($style) "
style = "green"
truncation_length = 32
truncation_symbol = "…"

[git_status]
format = "[$conflicted$stashed$staged$modified$untracked$ahead_behind]($style)"
style = ""
conflicted = "[~$count](red) "
stashed = "[*$count](green) "
staged = "[+$count](yellow) "
modified = "[!$count](yellow) "
untracked = "[?$count](cyan) "
ahead = "[⇡$count](green)"
behind = "[⇣$count](green)"
diverged = "[⇣${behind_count}⇡${ahead_count}](green)"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[git_metrics]
disabled = false
format = "([+$added](green) )([-$deleted](red) )"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"
min_time = 2_000

[jobs]
format = "[$symbol$number]($style) "
style = "blue bold"
symbol = "✦"
number_threshold = 1

[hostname]
ssh_only = true
format = "[$hostname]($style) "
style = "yellow"

[username]
# show_always = true
format = "[$user]($style) "
style_user = "yellow bold"
style_root = "red bold"

[time]
disabled = false
format = "[$time]($style)"
style = "bright-black"
time_format = "%H:%M:%S"

[status]
disabled = false
format = "[✘ $status]($style) "
style = "red"

[sudo]
disabled = false
format = "[$symbol]($style)"
symbol = "🔓"
style = "yellow"

[python]
format = "[$virtualenv]($style) "
style = "bright-black"
detect_extensions = []
detect_files = []
