local M = {}

function M.get(c, bg)
  return {
    Normal = { fg = c.fg, bg = bg },
    Terminal = { fg = c.fg, bg = bg },
    EndOfBuffer = { fg = c.bg0, bg = bg },
    FoldColumn = { fg = c.fg, bg = bg },
    Folded = { fg = c.fg, bg = bg },
    SignColumn = { fg = c.fg, bg = bg },
    ToolbarLine = { fg = c.fg },
    Cursor = { reverse = true },
    vCursor = { reverse = true },
    iCursor = { reverse = true },
    lCursor = { reverse = true },
    CursorIM = { reverse = true },
    CursorColumn = { bg = c.bg_hl },
    CursorLine = { bg = c.bg_hl },
    ColorColumn = { bg = c.bg_hl },
    CursorLineNr = { fg = c.fg },
    LineNr = { fg = c.grey },
    Conceal = { fg = c.grey, bg = c.bg_hl },
    Added = { fg = c.green },
    Removed = { fg = c.red },
    Changed = { fg = c.blue },
    DiffAdd = { bg = c.bg1 },
    DiffChange = { bg = c.bg1 },
    DiffDelete = { bg = c.bg1 },
    DiffText = { bg = c.bg1 },
    DiffAdded = { fg = c.green },
    DiffChanged = { fg = c.blue },
    DiffRemoved = { fg = c.red },
    DiffDeleted = { fg = c.red },
    DiffFile = { fg = c.cyan },
    DiffIndexLine = { fg = c.grey },
    Directory = { fg = c.blue },
    ErrorMsg = { fg = c.red, bold = true },
    WarningMsg = { fg = c.yellow, bold = true },
    MoreMsg = { fg = c.blue, bold = true },
    CurSearch = { fg = c.bg0, bg = c.orange },
    IncSearch = { fg = c.bg0, bg = c.orange },
    Search = { fg = c.fg, bg = c.bg3 },
    Substitute = { fg = c.bg0, bg = c.green },
    MatchParen = { bg = c.grey },
    NonText = { fg = c.grey },
    Whitespace = { fg = c.grey },
    SpecialKey = { fg = c.grey },
    Pmenu = { fg = c.fg, bg = c.bg_hl },
    PmenuSbar = { bg = c.bg_hl },
    PmenuSel = { fg = c.bg0, bg = c.blue },
    WildMenu = { fg = c.bg0, bg = c.blue },
    PmenuThumb = { bg = c.grey },
    Question = { fg = c.yellow },
    SpellBad = { undercurl = true, sp = c.red },
    SpellCap = { undercurl = true, sp = c.yellow },
    SpellLocal = { undercurl = true, sp = c.blue },
    SpellRare = { undercurl = true, sp = c.purple },
    StatusLine = { bg = bg },
    StatusLineTerm = { fg = c.fg, bg = c.bg1 },
    StatusLineNC = { bg = bg },
    StatusLineTermNC = { fg = c.grey, bg = c.bg_hl },
    TabLine = { fg = c.fg, bg = c.bg_hl },
    TabLineFill = { fg = c.grey, bg = c.bg_hl },
    TabLineSel = { fg = c.bg0, bg = c.fg },
    WinSeparator = { fg = c.bg3 },
    Visual = { bg = c.bg3 },
    VisualNOS = { bg = c.bg1, underline = true },
    QuickFixLine = { fg = c.blue, underline = true },
    Debug = { fg = c.yellow },
    debugPC = { fg = c.bg0, bg = c.green },
    debugBreakpoint = { fg = c.bg0, bg = c.red },
    ToolbarButton = { fg = c.bg0, bg = c.blue },
    FloatBorder = { fg = c.grey, bg = c.bg_hl },
    NormalFloat = { fg = c.fg, bg = c.bg_hl },
    WinBar = { fg = c.fg, bg = bg },
    WinBarNC = { fg = c.grey, bg = bg },
  }
end

return M
