local M = {}

function M.get(c, _)
  return {
    -- Standard syntax
    String = { fg = c.green },
    Character = { fg = c.orange },
    Number = { fg = c.orange },
    Float = { fg = c.orange },
    Boolean = { fg = c.orange },
    Type = { fg = c.yellow },
    Structure = { fg = c.yellow },
    StorageClass = { fg = c.yellow },
    Identifier = { fg = c.red },
    Constant = { fg = c.cyan },
    PreProc = { fg = c.purple },
    PreCondit = { fg = c.purple },
    Include = { fg = c.purple },
    Keyword = { fg = c.purple },
    Define = { fg = c.purple },
    Typedef = { fg = c.yellow },
    Exception = { fg = c.purple },
    Conditional = { fg = c.purple },
    Repeat = { fg = c.purple },
    Statement = { fg = c.purple },
    Macro = { fg = c.red },
    Error = { fg = c.purple },
    Label = { fg = c.purple },
    Special = { fg = c.red },
    SpecialChar = { fg = c.red },
    Function = { fg = c.blue },
    Operator = { fg = c.purple },
    Title = { fg = c.cyan },
    Tag = { fg = c.green },
    Delimiter = { fg = c.white },
    Comment = { fg = c.grey, italic = true },
    SpecialComment = { fg = c.grey, italic = true },
    Todo = { fg = c.red, italic = true },

    -- Language: C / C++
    cInclude = { fg = c.blue },
    cStorageClass = { fg = c.purple },
    cTypedef = { fg = c.purple },
    cDefine = { fg = c.cyan },
    cppStatement = { fg = c.purple, bold = true },

    -- Language: Markdown
    markdownBlockquote = { fg = c.grey },
    markdownBold = { bold = true },
    markdownBoldDelimiter = { fg = c.grey },
    markdownCode = { fg = c.green },
    markdownCodeBlock = { fg = c.green },
    markdownCodeDelimiter = { fg = c.yellow },
    markdownH1 = { fg = c.red, bold = true },
    markdownH2 = { fg = c.purple, bold = true },
    markdownH3 = { fg = c.orange, bold = true },
    markdownH4 = { fg = c.red, bold = true },
    markdownH5 = { fg = c.purple, bold = true },
    markdownH6 = { fg = c.orange, bold = true },
    markdownHeadingDelimiter = { fg = c.grey },
    markdownHeadingRule = { fg = c.grey },
    markdownId = { fg = c.yellow },
    markdownIdDeclaration = { fg = c.red },
    markdownItalic = { italic = true },
    markdownItalicDelimiter = { fg = c.grey, italic = true },
    markdownLinkDelimiter = { fg = c.grey },
    markdownLinkText = { fg = c.red },
    markdownLinkTextDelimiter = { fg = c.grey },
    markdownListMarker = { fg = c.red },
    markdownOrderedListMarker = { fg = c.red },
    markdownRule = { fg = c.purple },
    markdownUrl = { fg = c.blue, underline = true },
    markdownUrlDelimiter = { fg = c.grey },
    markdownUrlTitleDelimiter = { fg = c.green },
  }
end

return M
