[manager]
show_hidden = true
sort_dir_first = true
linemode = "size_and_mtime"
show_symlink = true

[opener]
edit = [
  { run = '${EDITOR:-vim} "$@"', block = true },
]

[open]
prepend_rules = [
  { url = "*.md", use = "edit" },
]

[plugin]
prepend_previewers = [
  { url = "*.md", run = "piper", args = ['-- CLICOLOR_FORCE=1 glow -w=$w -s=dark "$1"'] },
  { mime = "{image,audio,video}/*", run = "mediainfo" },
  { url = "*.{docx,xlsx,pptx,odt,ods,odp}", run = "office" },
]

prepend_fetchers = [
  { id = "git", group = "file", url = "*", run = "git" },
  { id = "git", group = "directory", url = "*/", run = "git" },
]
