return {
    rosewater = "#F5E0DC",
    flamingo  = "#F2CDCD",
    pink      = "#F5C2E7",
    mauve     = "#CBA6F7",
    red       = "#F38BA8",
    maroon    = "#EBA0AC",
    peach     = "#FAB387",
    yellow    = "#F9E2AF",
    green     = "#A6E3A1",
    teal      = "#94E2D5",
    sky       = "#89DCEB",
    sapphire  = "#74C7EC",
    blue      = "#89B4FA",
    lavender  = "#B4BEFE",
}
